services:
  - type: web
    name: link-to-pdf
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PDF_DIR
        value: /tmp/linkpdf
